services:
    davidyin.simplecdn.listener:
        class: davidyin\simplecdn\event\listener
        arguments:
            - '@template'
            - '@config'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }
